#!/usr/bin/env python3
"""Turn the built web UI into a gzipped HTTP response in flash.

The output is a C file containing ONE byte array: the complete HTTP response
head, then CRLFCRLF, then the gzip stream. It is emitted contiguously because
lwIP's httpd sends a file marked FS_FILE_FLAGS_HEADER_INCLUDED verbatim in a
single block -- so baking the headers in is what lets the page carry
`Content-Encoding: gzip` at all, which httpd's generated headers cannot express.

Content-Length is computed here rather than at run time for the same reason:
once the headers are bytes in flash, they have to already be correct.

    python3 tools/embed_website.py website/dist \
        --output ILT_OS/Applications/ILT_TESTRIG/WebsiteAsset.c
"""

import argparse
import gzip
import pathlib
import re
import sys

CRLF = "\r\n"


def inline_assets(dist: pathlib.Path) -> str:
    """Fold the CSS and JS bundles into index.html.

    The board serves only what it is asked for and has no route to a CDN, so a
    page that still referenced /assets/*.js would be a blank screen. One file
    also means one flash object and one Content-Length.
    """
    html = (dist / "index.html").read_text()

    def css_repl(m: re.Match) -> str:
        href = m.group(1).lstrip("/")
        return "<style>" + (dist / href).read_text() + "</style>"

    def js_repl(m: re.Match) -> str:
        tag, src = m.group(0), m.group(1).lstrip("/")
        code = (dist / src).read_text()

        # KEEP type="module". Vite puts the script in <head>, and a module
        # script is DEFERRED -- it runs after the document is parsed. A plain
        # inline <script> runs immediately, so createRoot() would look for
        # #root while the body has not been parsed yet and React would throw
        # "target container is not a DOM element" on a blank page. `defer` is
        # ignored on inline scripts, so the module type is what carries it.
        module = ' type="module"' if 'type="module"' in tag else ""

        # A literal </script> inside the code would end the tag early. The
        # current bundle has none, but that is a property of today's minifier
        # output, not a guarantee.
        code = code.replace("</script>", "<\\/script>")

        return f"<script{module}>" + code + "</script>"

    html = re.sub(r'<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"[^>]*>', css_repl, html)
    html = re.sub(r'<script[^>]+src="([^"]+)"[^>]*>\s*</script>', js_repl, html)

    if "/assets/" in html:
        sys.exit("embed_website: an asset reference survived inlining; "
                 "the page would load blank on the board")
    return html


def build_response(html: str, level: int) -> bytes:
    """The full HTTP response: baked headers plus the gzip stream."""
    # mtime=0 so the same input always produces the same bytes -- a rebuild that
    # changes nothing should not change the firmware image.
    body = gzip.compress(html.encode("utf-8"), compresslevel=level, mtime=0)

    head = CRLF.join([
        "HTTP/1.0 200 OK",
        "Server: ILT_TESTRIG",
        "Content-Type: text/html; charset=utf-8",
        "Content-Encoding: gzip",
        f"Content-Length: {len(body)}",
        # The page is baked into the image, so it only changes when the board is
        # reflashed. Letting a browser cache it makes the rig feel immediate on
        # every visit after the first.
        "Cache-Control: public, max-age=600",
        "Connection: close",
    ]) + CRLF + CRLF

    return head.encode("ascii") + body


def emit_c(response: bytes, raw_len: int, out: pathlib.Path, section: str) -> None:
    rows = []
    for i in range(0, len(response), 16):
        chunk = response[i:i + 16]
        rows.append("    " + " ".join(f"0x{b:02x}," for b in chunk))

    saved = 100 - (100 * len(response) // raw_len) if raw_len else 0

    out.write_text(f"""/* GENERATED by tools/embed_website.py -- do not edit.
 *
 * The web UI as one complete HTTP response: headers, then a gzip stream.
 * {raw_len:,} bytes of HTML in, {len(response):,} bytes out ({saved}% smaller).
 *
 * Served verbatim by ILT_OS/Lib/Net/HttpServer.cpp, which marks the route
 * FS_FILE_FLAGS_HEADER_INCLUDED so httpd does not prepend headers of its own.
 * Regenerate with tools/embed-website.sh after changing anything under website/.
 */

#include <stddef.h>
#include <stdint.h>

/* The dedicated flash region exists only on the MCU boards; the host build
 * links this as ordinary rodata. The board's CMakeLists defines the macro. */
#ifdef ILT_WEBSITE_SECTION
#define ILT_WEBSITE_ATTR __attribute__((section("{section}"), aligned(4)))
#else
#define ILT_WEBSITE_ATTR __attribute__((aligned(4)))
#endif

const uint8_t ilt_website_response[] ILT_WEBSITE_ATTR = {{
{chr(10).join(rows)}
}};

const size_t ilt_website_response_len = sizeof(ilt_website_response);
""")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("dist", type=pathlib.Path, help="Vite output directory")
    ap.add_argument("--output", type=pathlib.Path, required=True)
    ap.add_argument("--section", default=".website",
                    help='linker section, or "" to leave it to the compiler')
    ap.add_argument("--level", type=int, default=9)
    args = ap.parse_args()

    if not (args.dist / "index.html").exists():
        sys.exit(f"embed_website: no index.html in {args.dist} -- run `npm run build` first")

    html = inline_assets(args.dist)
    response = build_response(html, args.level)

    section = args.section
    args.output.parent.mkdir(parents=True, exist_ok=True)
    emit_c(response, len(html.encode()), args.output, section)

    print(f"  html   {len(html.encode()):>8,} bytes")
    print(f"  gzip   {len(response):>8,} bytes  (with headers)")
    print(f"  ->     {args.output}")


if __name__ == "__main__":
    main()
