/**
  ******************************************************************************
  * @file    HttpServer.h
  * @brief   A small web server: lwIP's httpd, with the pages registered in C++.
  *
  * lwIP's httpd speaks HTTP but gets its content through the fs_open/fs_read/
  * fs_close API in lwip/apps/fs.h, which upstream backs with a C array
  * generated by the makefsdata host tool. This class implements that API over a
  * route table instead, so pages are registered at run time from ordinary C++
  * and no generated blob has to be checked in.
  *
  *     static const char kIndex[] = "<!doctype html>...";
  *
  *     auto &http = ilt::net::HttpServer::instance();
  *     http.addPage("/index.html", kIndex);
  *     http.addPage("/status.json", &renderStatus);
  *     http.start();
  *
  * The response's Content-Type comes from the extension in the registered path,
  * which is how lwIP's httpd has always decided it: .html, .htm, .css, .js,
  * .json, .xml, .png, .gif, .jpg, .ico and .pdf are recognised, and anything
  * else is served as text/plain. Name routes accordingly -- "/status.json",
  * not "/status".
  *
  * Nothing here is board-specific; it needs only that NetworkStack has been
  * started.
  ******************************************************************************
  */

#ifndef ILT_OS_LIB_NET_HTTPSERVER_H
#define ILT_OS_LIB_NET_HTTPSERVER_H

#include <cstddef>
#include <cstdint>

namespace ilt::net {

/**
 * @brief Renders a response body on demand.
 *
 * Called once per request for a dynamic route, from lwIP's tcpip_thread.
 *
 * @param buffer   Scratch to write the body into; not zero-initialised.
 * @param capacity Bytes available, HttpServer::renderCapacity().
 * @param query    The request's query parameters; empty if there were none.
 * @return Bytes written, or 0 to answer 404. Never more than @p capacity.
 *
 * @note A route with parameters is rendered TWICE per request: once from
 *       fs_open() with an empty query, because httpd requires the body to
 *       exist before it parses parameters, and again once they are available.
 *       Renders must therefore be pure -- produce output, change nothing.
 *
 * @note Runs in tcpip_thread, so it must not block: no osDelay, no waiting on
 *       a mutex another thread holds while it talks to the network. Read a
 *       shared snapshot and format it.
 */
/**
 * @brief The query parameters of one request.
 *
 * Wraps the arrays lwIP's httpd has already split out of the URI, so routes do
 * not parse query strings themselves. Valid only for the duration of the render
 * call that receives it.
 */
class HttpQuery
{
public:
    HttpQuery() noexcept = default;
    HttpQuery(int count, char **names, char **values) noexcept
        : count_(count < 0 ? 0 : count), names_(names), values_(values)
    {
    }

    /** @brief Number of parameters supplied. */
    int count() const noexcept { return count_; }

    /**
     * @brief The raw value of @p name, or nullptr if it was not supplied.
     *
     * A parameter given with no value ("?probe") yields an empty string, which
     * is distinct from absent.
     */
    const char *get(const char *name) const noexcept;

    /**
     * @brief Parse @p name as an unsigned integer.
     *
     * Accepts decimal, or hexadecimal with an "0x" prefix so a lens mask can be
     * written the way the protocol documents it.
     *
     * @return false if absent or not a number, leaving @p out untouched.
     */
    bool getUint(const char *name, std::uint32_t &out) const noexcept;

private:
    int    count_{0};
    char **names_{nullptr};
    char **values_{nullptr};
};

using HttpRenderFn = std::size_t (*)(char *buffer, std::size_t capacity,
                                     const HttpQuery &query) noexcept;

/**
 * @brief The board's HTTP server on port 80.
 *
 * A singleton because lwIP's httpd is itself a single global listener; there is
 * nothing useful a second instance could do. Constructed before main() with no
 * side effects.
 */
class HttpServer
{
public:
    static HttpServer &instance() noexcept;

    HttpServer(const HttpServer &)            = delete;
    HttpServer &operator=(const HttpServer &) = delete;

    /**
     * @brief Serve a NUL-terminated string held in flash.
     *
     * @param path Request path, leading slash included, e.g. "/index.html".
     *             Stored by pointer, so it must outlive the server -- a string
     *             literal is the expected argument.
     * @param body Response body. Also stored by pointer and never copied.
     * @return false if the route table is full or an argument is null.
     */
    bool addPage(const char *path, const char *body) noexcept;

    /** @brief As above, for content that is not NUL-terminated. */
    bool addPage(const char *path, const char *body, std::size_t length) noexcept;

    /**
     * @brief Serve a complete, pre-built HTTP response verbatim.
     *
     * The bytes must be the whole thing -- status line, headers, CRLFCRLF,
     * body -- because httpd is told the file carries its own headers and will
     * not add any. That is the only way to send a header it cannot generate,
     * which is what a gzipped page needs: `Content-Encoding: gzip`.
     *
     * Used for the embedded web UI, which is generated by
     * tools/embed_website.py and lives in its own flash region. The response is
     * sent straight from flash, so it costs no RAM and no render buffer.
     *
     * @param path     Request path, e.g. "/index.html".
     * @param response The complete response; stored by pointer, never copied.
     * @param length   Its size in bytes.
     */
    bool addRawResponse(const char *path, const void *response,
                        std::size_t length) noexcept;

    /**
     * @brief Serve content rendered per request.
     *
     * Each in-flight request for a dynamic route holds one render buffer;
     * renderBufferCount() of them exist. If they are all in use the request is
     * answered 404 rather than being made to wait, so a burst degrades instead
     * of stalling tcpip_thread.
     */
    bool addPage(const char *path, HttpRenderFn render) noexcept;

    /**
     * @brief Bind port 80 and begin serving.
     *
     * Call after NetworkStack::start() and after every addPage(); routes added
     * afterwards are still picked up, but registering them first avoids serving
     * a 404 to a client that arrives in between.
     *
     * Safe to call from any thread: the actual httpd_init() is marshalled onto
     * tcpip_thread, and this returns once it has run.
     *
     * @return false if already running, or if lwIP could not be reached.
     */
    bool start() noexcept;

    /** @brief Whether start() has completed. */
    bool isRunning() const noexcept;

    /** @brief Routes registered so far. */
    std::size_t routeCount() const noexcept;

    /** @brief Maximum routes, fixed at build time by ILT_HTTP_MAX_ROUTES. */
    static std::size_t routeCapacity() noexcept;

    /** @brief Bytes a dynamic route may render, ILT_HTTP_RENDER_BYTES. */
    static std::size_t renderCapacity() noexcept;

    /** @brief Concurrent dynamic renders supported, ILT_HTTP_RENDER_BUFFERS. */
    static std::size_t renderBufferCount() noexcept;

    /** @brief Requests matched to a route since boot. Cheap health signal. */
    std::uint32_t requestsServed() const noexcept;

    /**
     * @brief Lookups that matched no route since boot.
     *
     * Not the same as failed requests: when a client asks for "/", httpd probes
     * /index.shtml, /index.ssi and /index.shtm before reaching /index.html, so
     * one successful page load adds three misses here. Useful as a trend, not
     * as an absolute count.
     */
    std::uint32_t requestsRejected() const noexcept;

private:
    HttpServer() noexcept = default;
};

} // namespace ilt::net

#endif /* ILT_OS_LIB_NET_HTTPSERVER_H */
