/**
  ******************************************************************************
  * @file    BoardEthernet.cpp
  * @brief   NUCLEO-F767ZI implementation of Bsp/Ethernet.h.
  *
  * The board carries an SMSC LAN8742A PHY on RMII. All of the driving is done
  * by the CubeMX-generated LWIP/Target/ethernetif.c; this file only publishes
  * it through the board-neutral BSP interface and owns the MAC address.
  ******************************************************************************
  */

#include "Bsp/Ethernet.h"

#include "ethernetif.h"
#include "main.h"

namespace bsp::eth {

bool available() noexcept
{
    return true;
}

netif_init_fn netifInit() noexcept
{
    return &ethernetif_init;
}

void pollLink(struct netif *netif) noexcept
{
    /* CubeMX generates this into ethernetif.c: it reads the LAN8742 status
       registers, and on a change applies the negotiated speed/duplex to the MAC
       and moves the netif up or down. It must run in tcpip_thread context,
       which is where NetworkStack's sys_timeout puts it. */
    ethernet_link_check_state(netif);
}

void macAddress(std::uint8_t out[6]) noexcept
{
    /* Fold the 96-bit unique device ID down to 24 bits of host part. Collisions
       need two boards whose IDs agree in that fold, which is vanishingly
       unlikely across the handful of boards this firmware runs on, and far
       better than the fixed 00:80:E1:00:00:00 CubeMX emits -- two of those on
       one segment produce an ARP fight that is miserable to diagnose. */
    const std::uint32_t uid = HAL_GetUIDw0() ^ HAL_GetUIDw1() ^ HAL_GetUIDw2();

    /* 0x02 in the first octet: locally administered (bit 1 set) and unicast
       (bit 0 clear), so we are not squatting on any vendor's OUI. */
    out[0] = 0x02U;
    out[1] = 0x00U;
    out[2] = 0x00U;
    out[3] = static_cast<std::uint8_t>((uid >> 16) & 0xFFU);
    out[4] = static_cast<std::uint8_t>((uid >> 8) & 0xFFU);
    out[5] = static_cast<std::uint8_t>(uid & 0xFFU);
}

} // namespace bsp::eth

/**
 * @brief C shim so the CubeMX-generated ethernetif.c can reach the C++ BSP.
 *
 * ethernetif.c is regenerated by CubeMX and stays plain C; this is the one
 * symbol it calls into on our side.
 */
extern "C" void BSP_ETH_GetMacAddress(std::uint8_t *out)
{
    bsp::eth::macAddress(out);
}
